### ISSUE TITLE
Unable to run buckley-leverett.ipynb :bug: 

### ISSUE THREAD

**Issue by amandersillinois** [frank1010111/pywaterflood#78]
I have successfully installed pywaterflood and can run 7-minutes-to-pywaterflood.ipynb, choosing-crm.ipynb, and multiwell-productivity-index.ipynb.  However, I can't run /buckley-leverett.ipynb

This is the error I get when trying to run the first cell in the notebook.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 6
      3 import seaborn as sns
      4 import pandas as pd
----> 6 from pywaterflood.buckleyleverett import Reservoir, water_front_velocity, breakthrough_sw

ModuleNotFoundError: No module named 'pywaterflood.buckleyleverett'

**Comment by frank1010111** [comment]
Thank you for raising this issue. I think the problem is that the `buckleyleverett` submodule has not been released on pywaterflood's PyPI page. Therefore, wheels that have it included have to be hand-rolled. I am nearing the 0.4 release where it will be added. 

In the meantime, you can install pywaterflood with the buckleyleverett submodule by following the documentation in the [Contributing guide](https://github.com/frank1010111/pywaterflood/blob/master/CONTRIBUTING.md#get-started).

Or, if you have rust installed on your system, you might be able to run 
```
pip install git+https://github.com/frank1010111/pywaterflood.git
```

Let me know if that fixes things, and I hope Buckley-Leverett is useful for you.

**Comment by amandersillinois** [comment]
Thanks!
